apiVersion: v1
kind: Secret

metadata:
  name: backend-secrets
  namespace: speedmotors

type: Opaque

stringData:
  DATABASE_URL: postgresql://speedmotors:speedmotors123@postgres:5432/speedmotors

  JWT_SECRET: speedmotors_super_secret_key_123!
  JWT_EXPIRES_IN: 7d

  CLOUDINARY_CLOUD_NAME: 
  CLOUDINARY_API_KEY: 
  CLOUDINARY_API_SECRET: 
