apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: speedmotors
type: Opaque
stringData:
  POSTGRES_DB: speedmotors
  POSTGRES_USER: speedmotors
  POSTGRES_PASSWORD: speedmotors123